### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by Catsvilles** [andrasbacsai/sapper-tailwind-starter#1]
Hey, I'm trying to redesign my production Sappe app to Tailwind and need of a use of process in my comoponents, but for some reason I'm getting this error while with other starters I don't. Any idea what I messed up or need to setup? Thanks :)

**Comment by andrasbacsai** [comment]
Hey, the `process` object could only available on the server-side. If you need to access some environment variable, you need to populate it through the `sapper.middleware` in `server.js`:

```javascript
sapper.middleware({
 session: (req, res) => ({
  home: process.env.HOME
 })
})
```
Then you can access it on the client-side with:
```typescript
<script>
 import { stores } from '@sapper/app';
 const { session } = stores();
 console.log($session.home)
</script>
```

I hope it helps.

**Comment by Catsvilles** [comment]
Hey, thanks for getting back to me! There are so many reasons for this error actually, somehow I fixed it (not really sure how), after that I got many other errors but I guess I just have to pull through, Sapper is really unstable framework and every starter templates has it's own unique stuff we have to consider :)

**Comment by andrasbacsai** [comment]
Let's wait for [SvelteKit](https://svelte.dev/blog/whats-the-deal-with-sveltekit)! (I'm excited)
